### PR TITLE
Support standard streamid syntax with unit tests

### PR DESCRIPTION
**Pull request by gpmidi**
An updated version of #39 with unit tests. Also added support for passing on the `username` to the upstream AAA. Plus a few random non-bug fixes I ran across while I was at it.

### CODE REVIEW

**Comment by gpmidi** [comment]
@iSchluff I'm working on unit tests for this and noticed that the [TestServerImpl_GetStatistics](https://github.com/gpmidi/srtrelay/blob/6bbb6e6414868f6e052c1b8e712ef9e7dca59cf7/srt/server_test.go#L28) test fails. The tl;dr is that it's old vs new format. I can either update the test to use the SRT defined spec or figure out a way to base the answer on what was sent to the server in the first place. Thoughts? 

For now I've just reverted the output to the pre-change version just so the behavior doesn't change on dependent apps. 

```
=== RUN   TestServerImpl_GetStatistics
    server_test.go:52: Invalid stream statistics: got {s1 srt://testserver.de:1337?streamid=#!::m=request,r=s1 2 2024-11-25 14:48:26.374969306 -0500 EST m=+0.000745398}, expected {s1 srt://testserver.de:1337?streamid=play/s1 2 2024-11-25 14:48:26.374969306 -0500 EST m=+0.000745398}
--- FAIL: TestServerImpl_GetStatistics (0.00s)
```

**Comment by iSchluff** [comment]
I'm not super attached to the url returned in GetStatistics. The main goal is having something that ffmpeg understands. So if the new format still works with ffplay I am fine with changing the result.

**Comment by gpmidi** [comment]
@iSchluff Thanks! I'll test it locally with ffmpeg to double check and report back.

**Comment by gpmidi** [comment]
ffplay works fine with the new url format

**Comment by gpmidi** [comment]
@iSchluff Ready for review. Can close out #39 when this is merged :)

**Comment by gpmidi** [comment]
@iSchluff Any chance on a PR review?

**Comment by gpmidi** [comment]
@iSchluff Any word on a review? Plz? ;)

**Comment by danimo** [comment]
Quick heads-up: I have rebased your branch on top of our ongoing work to update the ecosystem. Unfortunately, the changes you are proposing are above my skill level wrt the SRT format. @iSchluff seems busy at the moment, please be patient.

**Comment by gpmidi** [comment]
@danimo Ah cool, thanks for the update :)

**Comment by iSchluff** [comment]
Rebased and merged manually

**Pull request closed without merging**
